keys:
  - &chewie age1wn2ash827uq9nlkfctr3yhj5k30mnatldwwvxnewhtuuaq8x2fdq84u8x6
  - &obiwan age1vk8cvtxpvjqwrda303fezn3flq2vugnfldtcuu9jjg7u49g4nqvqxwgjl3
  - &yoda age180hurage7swmnf3he3pj0e3333f9yeygl2hy7pelv2pf06f53vvqng2xj2
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *chewie
      - *obiwan
      - *yoda
