# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "@augmentcode/auggie" = nodeEnv.buildNodePackage {
    name = "_at_augmentcode_slash_auggie";
    packageName = "@augmentcode/auggie";
    version = "0.19.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@augmentcode/auggie/-/auggie-0.19.0.tgz";
      sha512 = "N3LdAOKk8TeAtUB+oZJwYKzp5d0p0dGVfN9gW+qFxOzGg8vGS0uS72hKtgpKoCuDB2adYSS5i5CjDw+apD95qg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Auggie CLI Client by Augment Code";
      homepage = "https://augmentcode.com";
      license = "SEE LICENSE IN LICENSE.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
